### ISSUE TITLE
Its Not Working with HP LaserJet Pro M15w

### ISSUE THREAD

**Issue by alijamal14** [frogmorecs/RawPrint#27]
Salaam
Its Not Working with HP LaserJet Pro M15w
The command is sent to printer the printer blinks but nothing is printed.

**Comment by kuberP** [comment]
Reason 1 - The raw file is an highly secured file so your raw file is going to the spooler but windows is restricting your application due to less security settings. 
Increase the security permissions of your application 

Reason 2- Raw file is of two types 1- EMF Raw (Proprietary windows print command) there is no documentation or command through which you can print a raw emf. A raw emf can be converted into a .emf ( vector image) and then sent to the printer to be printed

2- ESC/POS Raw (Epson propriety print command) - This is an open source print command by epson if you have an esc/pos raw file then you can send the raw file directly to the printer with a right print command. 

Solution - Check the raw file you are printing by pausing your printer driver and go to the below path 
C:\Windows\System32\spool\PRINTERS
and check the raw print file which is being to the printer check the print command type and if your raw file is esc/pos you will see the text content you are trying to print if it is raw emf you will see encrypted characters (you can also search the word 'EMF' after opening the file in a notepad.
After this try to research for a good print command and it will start working 

Make sure your print command is just sending the file to be printed without any other specifications

**Comment by tonyedgecombe** [comment]
You can only send a file to the printer that is formatted for the printer. Text or general PDF files won't work.

**Comment by alijamal14** [comment]
> You can only send a file to the printer that is formatted for the printer. Text or general PDF files won't work.

Thank You. @tonyedgecombe  Can i convert PDF to printer formatted file in C#. So I can print silently? If possible that would be a great help.

**Comment by tonyedgecombe** [comment]
Not with this software.

**Comment by alijamal14** [comment]
> Not with this software.

Thank You so much @tonyedgecombe. Is there any other way that you know?
