### ISSUE TITLE
Confusion with NuGet description

### ISSUE THREAD

**Issue by larrym** [frogmorecs/RawPrint#6]
In the RawPrint.nuspec file it says that the printer driver is bypassed. However in the summary message it says it supports v4 drivers! 

If the driver is bypassed why does it matter that the driver by v3 or v4?

**Comment by tonyedgecombe** [comment]
It's a function of the print spooler rather than driver, the path through the spooler changed with the introduction of v4 (or XPS based) printer drivers. The file still gets passed through unchanged but takes a slightly different path through the spooler.

See https://github.com/frogmorecs/RawPrint/blob/master/RawPrint/Printer.cs#L36 for the relevant line of code.
